import mysql.connector as cn
import tkinter as tk
from tkinter import *
import math

def exp_win1():
    root.geometry('800x750')
con= cn.connect(host='localhost', user='root', password='messiah10',database='calc_history')
mycon = con.cursor()
def exp_win2():
    root.geometry('520x750')
con= cn.connect(host='localhost', user='root', password='messiah10',database='calc_history')
mycon = con.cursor()
def sql_hist(k):
    mycon.execute("insert into calc_hist(history) values({})".format(k))
    con.commit()

def click(event):
    global scvalue
    text= event.widget.cget('text')
 
    try:
        if text == '=':
            if scvalue.get().isdigit():
                value = int(scvalue.get())
            elif 'cos' in scvalue.get():
                    d=screen.get()
                    v=int(d.replace('cos',''))
                    x=math.radians(v)
                    s=math.cos(x)
                    scvalue.set(round(s,3))
                    screen.update()
            elif 'sin' in scvalue.get():
                    d=screen.get()
                    v=int(d.replace('sin',''))
                    x=math.radians(v)
                    s=math.sin(x)
                    scvalue.set(round(s,3))
                    screen.update()
            elif 'tan' in scvalue.get():
                    d=screen.get()
                    v=int(d.replace('tan',''))
                    x=math.radians(v)
                    s=math.tan(x)
                    scvalue.set(round(s,3))
                    screen.update()
            elif 'csc' in scvalue.get():
                    d=screen.get()
                    v=int(d.replace('csc',''))
                    x=math.radians(v)
                    s=math.sin(x)
                    scvalue.set(round(1/s,3))
                    screen.update()
            elif 'sec' in scvalue.get():
                    d=screen.get()
                    v=int(d.replace('sec',''))
                    x=math.radians(v)
                    s=math.cos(x)
                    scvalue.set(round(1/s,3))
                    screen.update()
            elif 'cot' in scvalue.get():
                    d=screen.get()
                    v=int(d.replace('cot',''))
                    x=math.radians(v)
                    s=math.tan(x)
                    scvalue.set(round(1/s,3))
                    screen.update()
            else:
                value= eval(screen.get())
                scvalue.set(value)
                screen.update()
                sql_hist(value)

        elif text == 'C':
            scvalue.set("")
            screen.update()
        elif text == 'del':
            e= screen.get()
            screen.delete(len(e)-1)
            screen.update()
        elif text =='history':
            query= " select round(history) from calc_hist where id = (select max(id) from calc_hist)"
            mycon.execute(query)
            myrec= mycon.fetchone()
            print(myrec)
            h= myrec[0]
            print(h)
            scvalue.set(h)
            screen.update()
        elif text=='more':
            screen.update()
        elif text=='less':
            screen.update()
        else:
            scvalue.set(scvalue.get() + text)
            screen.update()
    except ZeroDivisionError:
        scvalue.set('not defined')
        screen.update()
root = tk.Tk()
root.geometry('520x750')
root.title('CALCULATOR')
root.configure(bg='black')
scvalue= StringVar()
scvalue.set("")
screen= Entry(root,textvar= scvalue, width='50',font=('lucida 35 bold'),bg='black',fg='white')
screen.pack(fill=X, ipadx=30,padx=20,pady=20)

f = Frame(root,bg='black',padx=0,pady=0,borderwidth=0, relief='flat')
b = Button(f,text = '1' ,padx=25,pady=20, font=('lucida 20 bold'),activebackground= 'black',bg='#23242c',fg='blue')
b.pack(side='left',padx=13,pady=20)
b.bind('<Button-1>', click)
f.pack()
b = Button(f,text = '2' ,padx=25,pady=20 , font=('lucida 20 bold'),activebackground= 'black',bg='#23242c',fg='blue')
b.pack(side='left',padx=18,pady=20)
b.bind('<Button-1>', click)
f.pack()
b = Button(f,text = '3' ,padx=25,pady=20, font=('lucida 20 bold'),activebackground= 'black',bg='#23242c',fg='blue')
b.pack(side='left',padx=18,pady=20)
b.bind('<Button-1>', click)
f.pack()
b = Button(f,text = 'C' ,padx=25,pady=20, font=('lucida 20 bold'),activebackground= 'black',bg='#23242c',fg='blue')
b.pack(side='left',padx=18,pady=20)
b.bind('<Button-1>', click)
f.pack()
b = Button(f,text = 'cos' ,padx=25,pady=20, font=('lucida 20 bold'),activebackground= 'black',bg='#23242c',fg='blue')
b.pack(side='left',padx=13,pady=20)
b.bind('<Button-1>', click)
f.pack()
b = Button(f,text = 'sec' ,padx=25,pady=20, font=('lucida 20 bold'),activebackground= 'black',bg='#23242c',fg='blue')
b.pack(side='left',padx=13,pady=20)
b.bind('<Button-1>', click)
f.pack()

f = Frame(root,bg='black')
b = Button(f,text = '4' ,padx=25,pady=20, font=('lucida 20 bold'),activebackground= 'black',bg='#23242c',fg='blue')
b.pack(side='left',padx=15,pady=20)
b.bind('<Button-1>', click)
f.pack()
b = Button(f,text = '5',padx=25,pady=20, font=('lucida 20 bold'),activebackground= 'black',bg='#23242c',fg='blue')
b.pack(side='left',padx=18,pady=20)
b.bind('<Button-1>', click)
f.pack()
b = Button(f,text = '6',padx=25,pady=20, font=('lucida 20 bold'),activebackground= 'black',bg='#23242c',fg='blue')
b.pack(side='left',padx=18,pady=20)
b.bind('<Button-1>', click)
f.pack()
b = Button(f,text = '+',padx=25,pady=20, font=('lucida 20 bold'),activebackground= 'black',bg='#23242c',fg='blue')
b.pack(side='left',padx=18,pady=20)
b.bind('<Button-1>', click)
f.pack()
b = Button(f,text = 'sin' ,padx=25,pady=20, font=('lucida 20 bold'),activebackground= 'black',bg='#23242c',fg='blue')
b.pack(side='left',padx=13,pady=20)
b.bind('<Button-1>', click)
f.pack()
b = Button(f,text = 'cot' ,padx=25,pady=20, font=('lucida 20 bold'),activebackground= 'black',bg='#23242c',fg='blue')
b.pack(side='left',padx=13,pady=20)
b.bind('<Button-1>', click)
f.pack()

f = Frame(root,bg='black')
b = Button(f,text = '7' ,padx=25,pady=20 , font=('lucida 20 bold'),activebackground= 'black',bg='#23242c',fg='blue')
b.pack(side='left',padx=19,pady=20)
b.bind('<Button-1>', click)
f.pack()
b = Button(f,text = '8',padx=25,pady=20, font=('lucida 20 bold'),activebackground= 'black',bg='#23242c',fg='blue')
b.pack(side='left',padx=18,pady=20)
b.bind('<Button-1>', click)
f.pack()
b = Button(f,text = '9',padx=25,pady=20, font=('lucida 20 bold'),activebackground= 'black',bg='#23242c',fg='blue')
b.pack(side='left',padx=18,pady=20)
b.bind('<Button-1>', click)
f.pack()
b = Button(f,text = '/',padx=25,pady=20, font=('lucida 20 bold'),activebackground= 'black',bg='#23242c',fg='blue')
b.pack(side='left',padx=18,pady=20)
b.bind('<Button-1>', click)
f.pack()
b = Button(f,text = 'tan' ,padx=25,pady=20, font=('lucida 20 bold'),activebackground= 'black',bg='#23242c',fg='blue')
b.pack(side='left',padx=13,pady=20)
b.bind('<Button-1>', click)
f.pack()
b = Button(f,text = 'x²' ,padx=25,pady=20, font=('lucida 20 bold'),activebackground= 'black',bg='#23242c',fg='blue')
b.pack(side='left',padx=13,pady=20)
b.bind('<Button-1>', click)
f.pack()
f = Frame(root,bg='black')
b = Button(f,text = '0' ,padx=26,pady=20, font=('lucida 20 bold'),activebackground= 'black',bg='#23242c',fg='blue')
b.pack(side='left',padx=18,pady=20)
b.bind('<Button-1>', click)
f.pack()
b = Button(f,text = '.',padx=15,pady=10, font=('lucida 20 bold'),activebackground= 'black',bg='#23242c',fg='blue')
b.pack(side='left',padx=13,pady=15)
b.bind('<Button-1>', click)
f.pack()
b = Button(f,text = '=' ,padx=15,pady=10, font=('lucida 20 bold'),activebackground= 'black',bg='#23242c',fg='blue')
b.pack(side='left',padx=11,pady=15)
b.bind('<Button-1>', click)
f.pack()
b = Button(f,text = '*' ,padx=15,pady=10, font=('lucida 20 bold'),activebackground= 'black',bg='#23242c',fg='blue')
b.pack(side='left',padx=12,pady=15)
b.bind('<Button-1>', click)
f.pack()
b = Button(f,text = '-' ,padx=15,pady=10, font=('lucida 20 bold'),activebackground= 'black',bg='#23242c',fg='blue')
b.pack(side='left',padx=18,pady=15)
b.bind('<Button-1>', click)
f.pack()
b = Button(f,text = 'csc' ,padx=25,pady=20, font=('lucida 20 bold'),activebackground= 'black',bg='#23242c',fg='blue')
b.pack(side='left',padx=13,pady=20)
b.bind('<Button-1>', click)
f.pack()

f = Frame(root,bg='black')
b = Button(f,text = 'del' ,padx=25,pady=20, font=('lucida 20 bold'),activebackground= 'black',bg='#23242c',fg='blue')
b.pack(side='left',padx=13,pady=20)
b.bind('<Button-1>', click)
f.pack()
b = Button(f,text = 'history' ,padx=25,pady=20, font=('lucida 20 bold'),activebackground= 'black',bg='#23242c',fg='blue')
b.pack(side='left',padx=13,pady=20)
b.bind('<Button-1>', click)
f.pack()
b = Button(f,text = 'more' ,padx=25,pady=20, font=('lucida 20 bold'),activebackground= 'black',bg='#23242c',fg='blue',command=exp_win1)
b.pack(side='left',padx=13,pady=20)
b.bind('<Button-1>', click)
f.pack()
b = Button(f,text = 'less' ,padx=25,pady=20, font=('lucida 20 bold'),activebackground= 'black',bg='#23242c',fg='blue',command=exp_win2)
b.pack(side='left',padx=13,pady=20)
b.bind('<Button-1>', click)
f.pack()
root.mainloop()



                
