
import tkinter as tk
from tkinter import *

def click(event):
    global scvalue
    text= event.widget.cget('text')
    if text == '=':
        if scvalue.get().isdigit():
            value = int(scvalue.get())
        else:
            value= eval(screen.get())
        scvalue.set(value)
        screen.update()
        sql_hist(value)
    elif text == 'C':
        scvalue.set("")
        screen.update()
    elif text == 'del':
        e= screen.get()
        screen.delete(len(e)-1)
        screen.update()
    else:
        scvalue.set(scvalue.get() + text)
        screen.update()
root = tk.Tk()
root.geometry('520x750')
root.title('CALCULATOR')
root.configure(bg='black')
scvalue= StringVar()
scvalue.set("")
screen= Entry(root,textvar= scvalue, width='50',font=('lucida 35 bold'),bg='black',fg='white')
screen.pack(fill=X, ipadx=30,padx=20,pady=20)

f = Frame(root,bg='black')
b = Button(f,text = '1' ,padx=25,pady=20, font=('lucida 20 bold'),activebackground= 'black',bg='#23242c',fg='blue')
b.pack(side='left',padx=13,pady=20)
b.bind('<Button-1>', click)
f.pack()
b = Button(f,text = '2' ,padx=25,pady=20 , font=('lucida 20 bold'),activebackground= 'black',bg='#23242c',fg='blue')
b.pack(side='left',padx=18,pady=20)
b.bind('<Button-1>', click)
f.pack()
b = Button(f,text = '3' ,padx=25,pady=20, font=('lucida 20 bold'),activebackground= 'black',bg='#23242c',fg='blue')
b.pack(side='left',padx=18,pady=20)
b.bind('<Button-1>', click)
f.pack()
b = Button(f,text = 'C' ,padx=25,pady=20, font=('lucida 20 bold'),activebackground= 'black',bg='#23242c',fg='blue')
b.pack(side='left',padx=18,pady=20)
b.bind('<Button-1>', click)
f.pack()

f = Frame(root,bg='black')
b = Button(f,text = '4' ,padx=25,pady=20, font=('lucida 20 bold'),activebackground= 'black',bg='#23242c',fg='blue')
b.pack(side='left',padx=15,pady=20)
b.bind('<Button-1>', click)
f.pack()
b = Button(f,text = '5',padx=25,pady=20, font=('lucida 20 bold'),activebackground= 'black',bg='#23242c',fg='blue')
b.pack(side='left',padx=18,pady=20)
b.bind('<Button-1>', click)
f.pack()
b = Button(f,text = '6',padx=25,pady=20, font=('lucida 20 bold'),activebackground= 'black',bg='#23242c',fg='blue')
b.pack(side='left',padx=18,pady=20)
b.bind('<Button-1>', click)
f.pack()
b = Button(f,text = '+',padx=25,pady=20, font=('lucida 20 bold'),activebackground= 'black',bg='#23242c',fg='blue')
b.pack(side='left',padx=18,pady=20)
b.bind('<Button-1>', click)
f.pack()

f = Frame(root,bg='black')
b = Button(f,text = '7' ,padx=25,pady=20 , font=('lucida 20 bold'),activebackground= 'black',bg='#23242c',fg='blue')
b.pack(side='left',padx=19,pady=20)
b.bind('<Button-1>', click)
f.pack()
b = Button(f,text = '8',padx=25,pady=20, font=('lucida 20 bold'),activebackground= 'black',bg='#23242c',fg='blue')
b.pack(side='left',padx=18,pady=20)
b.bind('<Button-1>', click)
f.pack()
b = Button(f,text = '9',padx=25,pady=20, font=('lucida 20 bold'),activebackground= 'black',bg='#23242c',fg='blue')
b.pack(side='left',padx=18,pady=20)
b.bind('<Button-1>', click)
f.pack()
b = Button(f,text = '/',padx=25,pady=20, font=('lucida 20 bold'),activebackground= 'black',bg='#23242c',fg='blue')
b.pack(side='left',padx=18,pady=20)
b.bind('<Button-1>', click)
f.pack()
f = Frame(root,bg='black')
b = Button(f,text = '0' ,padx=26,pady=20, font=('lucida 20 bold'),activebackground= 'black',bg='#23242c',fg='blue')
b.pack(side='left',padx=18,pady=20)
b.bind('<Button-1>', click)
f.pack()
b = Button(f,text = '.',padx=15,pady=10, font=('lucida 20 bold'),activebackground= 'black',bg='#23242c',fg='blue')
b.pack(side='left',padx=13,pady=15)
b.bind('<Button-1>', click)
f.pack()
b = Button(f,text = '=' ,padx=15,pady=10, font=('lucida 20 bold'),activebackground= 'black',bg='#23242c',fg='blue')
b.pack(side='left',padx=11,pady=15)
b.bind('<Button-1>', click)
f.pack()
b = Button(f,text = '*' ,padx=15,pady=10, font=('lucida 20 bold'),activebackground= 'black',bg='#23242c',fg='blue')
b.pack(side='left',padx=12,pady=15)
b.bind('<Button-1>', click)
f.pack()
b = Button(f,text = '-' ,padx=15,pady=10, font=('lucida 20 bold'),activebackground= 'black',bg='#23242c',fg='blue')
b.pack(side='right',padx=18,pady=15)
b.bind('<Button-1>', click)
f.pack()
f = Frame(root,bg='black')
b = Button(f,text = 'del' ,padx=25,pady=20, font=('lucida 20 bold'),activebackground= 'black',bg='#23242c',fg='blue')
b.pack(side='left',padx=13,pady=20)
b.bind('<Button-1>', click)
f.pack()
b = Button(f,text = 'history' ,padx=25,pady=20, font=('lucida 20 bold'),activebackground= 'black',bg='#23242c',fg='blue')
b.pack(side='left',padx=13,pady=20)
b.bind('<Button-1>', click)
f.pack()
root.mainloop()
